### ISSUE TITLE
Missing n in getCSVMSGrad

### ISSUE THREAD

**Issue by akhilnair95** [purushottamkar/ml19-20a#5]
In getCSVMSGrad

delb = C * g * y[i]

This equation is missing parameter n, ideally should be

delb = C * g * y[i] * n

**Comment by purushottamkar** [comment]
Already fixed several days ago in the following commit

https://github.com/purushottamkar/ml19-20a/commit/c3ef5fd300ffbc4325e92d9b1ff6ba0f0454db49

**Comment by akhilnair95** [comment]
The correction was made to  lec7-8.ipynb 
The same error exists in lec9.ipynb (getCSVMSGrad function)

**Comment by purushottamkar** [comment]
Fixed in the latest commit - thanks for pointing out. In the future, please point out file name and line number in your issues to avoid ambiguity.
